name: Build Extensions

on:
  push:
    tags: 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Chrome build
        run: |
          cp manifest/manifest.chrome.json manifest.json
          zip -r marklet-chrome.zip . -x "manifest/manifest.*.json"

      - name: Prepare Firefox build
        run: |
          cp manifest/manifest.firefox.json manifest.json
          zip -r marklet-firefox.zip . -x "manifest/manifest.*.json"

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/marklet-chrome.zip
            dist/marklet-firefox.zip
